spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      trigger-file: trigger.txt
    livereload:
      enabled: true
